#macro LAYER_LIGHTING       "Lighting"
#macro LAYER_ENVIRONMENT    "Environment"
#macro LAYER_BULLET         "Bullet"
#macro LAYER_CHARACTER      "Character"
#macro LAYER_ENEMY          "Enemy"
#macro LAYER_PARTICLE       "Particle"
#macro LAYER_TEXT           "Text"
#macro LAYER_TUTORIAL       "TutorialText"